### ISSUE TITLE
This is not issue but request to help

### ISSUE THREAD

**Issue by kinjar1988** [CuB3y0nd/1llusion#1]
Hi, your dots are awesome. I installed on endeavouros with gnome desktop and it works. But I request to you help me for below requirements. 

1. I am nee to Linux so I am not able to use ranger file manager. So I want to set Nautilus file manager key binding in your dots. I try many times but not successful. I tried to change bspwmrc file where you set ranger key binding. 

2.How can I change theme for some applications like Nautilus file manager, firefox time shift or pamac and vs code etc. 

3. Which theme you used across your rice? 

4. First I installed your dots in endeavouros without desktop. But after successful installed can't start bspwm. How can I start? 

Please help me to solve this problems as I don't want to remove your dots. It's perfectly works. 

Apologize for noon questions but I am new to window managers.

**Comment by CuB3y0nd** [comment]
Hi,

Glad you like my project!

About your question, I will answer them one by one below:

1. You can set particular application's startup shortcut key by edit `~/.config/bspwm/scripts/OpenApps` script. Here is an example, suppose Nautilus's start command is `nautilus`:

```shell
case "$1" in
--filemanager)
  nautilus
  ;;
*)
  echo "Invalid Option"
  ;;
esac
```

2. I use `LXAppearance` and `papirus-icon-theme` to customizes look and feel of applications and desktop. These two package are both provided at `install` script, you may need to pay attention to the installation command of gnome. Additionally, I don't know if there is support the same package name in gnome system environment.

3. I usually use the `emilia` theme, it’s more my aesthetic hahaha.

4. Execute `cp /etc/X11/xinit/xinitrc ~/.xinitrc` to get a local config first, then edit `~/.xinitrc` file and add `exec bspwm` under. You also need to comment out the content in the code snippet I gave. Then try use `startx` command, it will startup your bspwm.

```shell
#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

exec bspwm
```

**Comment by kinjar1988** [comment]
Thank you for your quick reply. One more help I want for network manager. I am using ethernet (wired) network. But in statusbar only wifi icon shows and when I search for network manager no application opening where I can configure my network. How can I change wifi icon to network icon and set click on to open network manager?

Once again thank you for your support. Please help to solve my problem.

**Comment by CuB3y0nd** [comment]
> Thank you for your quick reply. One more help I want for network manager. I am using ethernet (wired) network. But in statusbar only wifi icon shows and when I search for network manager no application opening where I can configure my network. How can I change wifi icon to network icon and set click on to open network manager?
> 
> Once again thank you for your support. Please help to solve my problem.

If you want change wifi icon, you can edit particular theme's `modules.ini` config file. In like `~/.config/bspwm/rices/emilia/modules.ini`.

If your theme does not show network status, always shows offline, you can read [wiki](https://github.com/CuB3y0nd/1llusion/wiki/Firsts-steps-after-installing). Edit `~/.config/bspwm/scripts/system.ini` file and set to correct values.

In addition, if you use Ethernet, you don't need a network management program application interface. Connecting the network cable will automatically configure the network, so you don't need to worry, just need set `system.ini` with the correct value.

If you really need a graphical network manager, I don't have any recommendations yet. I only use the command line interface, with `iwd` for wireless.

**Comment by kinjar1988** [comment]
Thank you once again for your support. I will try to install in endevouros without desktop as gnome has some issues.

**Comment by kinjar1988** [comment]
Hi I installed in endeavouros without any desktop. But some files do not copy and like Firefox and files and error showing " no dir in home/mozila/Firefox" etc.

I use lxapparence to change theme but can't. I download Dracula theme and installed successfully and use lxapperance to change the theme but can't change. Is there any other way to solve this ?

**Comment by CuB3y0nd** [comment]
> Hi I installed in endeavouros without any desktop. But some files do not copy and like Firefox and files and error showing " no dir in home/mozila/Firefox" etc.
> 
> I use lxapparence to change theme but can't. I download Dracula theme and installed successfully and use lxapperance to change the theme but can't change. Is there any other way to solve this ?

Can you use `LXAppearance` switch to other themes? Maybe `Dracula` theme is not supported by `LXAppearance`.

If `LXAppearance` is not help, I don't have other known way to solve it, sorry. You need search google by yourself.

About Firefox theme, do you sure you have already installed firefox on your system? Can you show me the full error info, so i can track the error.

Other ways, according to the content of the `install` script, you can copy firefox theme files manually.
